### ISSUE TITLE
Next link links to the current page on the first page

### ISSUE THREAD

**Issue by XomegaNet** [facebook/docusaurus#6183]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

In the latest release the _Next_ link shows a link to the current page on the first page or on a page with pagination_prev: null.
This was introduced in the latest beta-14.

### Steps to reproduce

1. Create a website with multiple pages.
2. Navigate to the first page.

### Expected behavior

The Next link should link to the next page.

### Actual behavior

The Next link links to the current page.

### Your environment

- Docusaurus version used: 2.0.0-beta.14

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
I don't observe the behavior [here](https://docusaurus.io/docs) or [here](https://docusaurus.io/docs/cli). Could you make a repro?

**Comment by XomegaNet** [comment]
Sorry, I just realized that it happens only when you have a link to that document in the sidebar.js, as follows
```
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Tutorial Basics',
      link: {type: 'doc', id: 'tutorial-basics/create-a-page'},
      items: [{type: 'autogenerated', dirName: 'tutorial-basics'}],
    },
  ],
```
If you open the `create-a-page` page, then the Next link will be to the current page. This also happens in beta-13, so maybe not a new bug.

Let me know if you still cannot repo, and I'll try to create an example.

**Comment by Josh-Cena** [comment]
As we discussed earlier in #6127, the current implementation makes the child autogenerated item and the parent category's index unaware of each other. Therefore when the `create-a-page` doc tries to generate its pagination, it finds the next doc to be the first in autogenerated—which happens to be itself.

When we allow you to exclude pages from autogenerated, both problems should be solved.

**Comment by XomegaNet** [comment]
So, if someone decides to use a `link` in the `category` sidebar item, but they **don't** want to exclude that page from the sidebar, would the Next navigation be still broken for them after you address the #6127?

**Comment by Josh-Cena** [comment]
Yes; that's what `pagination_next` is designed for.

**Comment by Josh-Cena** [comment]
Closing this. We can't prevent the following cases from happening:

- Page X appears twice consecutively;
- Page X is both the category index page and the first child item.

This rarely happens and detecting that would add unnecessary complexity to our algorithm. You'd rather want to use `pagination_next` because using the sidebar to generate navigation is just a default.
